### ISSUE TITLE
testcafe_2.default is not a function

### ISSUE THREAD

**Issue by screendriver** [percy/percy-testcafe#4]
I'm using [TestCafe](https://devexpress.github.io/testcafe/) together with [Percy](http://percy.io) in a [Gatsby](https://www.gatsbyjs.org) project that uses [TypeScript](http://www.typescriptlang.org	). My test looks like

```ts
import { Selector } from 'testcafe';
import percySnapshot from '@percy/testcafe';

fixture('Visual').page('http://localhost:9000');

test('with percy', async t => {
  await t
    .expect(Selector('title').innerText)
    .eql('This as a test');

  await percySnapshot(t, 'Integrate with Percy');
});
```

and I'm running the tests with

```
percy exec -- testcafe chrome:headless 'test/e2e/**/*.ts' --app 'gatsby serve'
```

Unfortunately I get the error

```sh
   1) TypeError: testcafe_2.default is not a function

      Browser: HeadlessChrome 76.0.3809 / Mac OS X 10.14.6

          6 |test('with percy', async t => {
          7 |  await t
          8 |    .expect(Selector('title').innerText)
          9 |    .eql('This as a test');
         10 |
       > 11 |  await percySnapshot(t, 'Integrate with Percy');
         12 |});
         13 |

         at <anonymous> (/Users/me/project/test/e2e/visual.test.ts:11:22)
         at fulfilled (/Users/me/project/test/e2e/visual.test.ts:5:58)
         at $$testcafe_test_run$$Wv1mGfF2z$$
      (/Users/me/project/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
         at $$testcafe_test_run$$Wv1mGfF2z$$
      (/Users/me/project/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
```

All other tests that are not calling `percySnapshot()` works perfectly.

**Comment by Robdel12** [comment]
Hey @screendriver, this sounds like a TypeScript import issue. Would you be able to try `import * as percySnapshot`?

**Comment by screendriver** [comment]
Oh man 🤦‍♂ How could I have overlooked that? Thank you very much 👍

**Comment by Robdel12** [comment]
Ha, no worries! That still gets me a lot of the time when using TS 😆

**Comment by CalinDale** [comment]
I'm having this problem as well, but I can't tell what the actual solution here is?
Is the solution to import percySnapshot with `import * as percySnapshot from '@percy/testcafe';`? That isn't working for me.
