### ISSUE TITLE
Finalizing SnapShot Error

### ISSUE THREAD

**Issue by brenzy** [percy/percy-testcafe#97]
I am getting random errors from percy that are causing percy builds to (randomly) fail.  

I am running a very simple test-cafe script that navigates to a series of urls and takes a percy snapshot at each url.  

I am running the test from localhost, and the issue happens when I test against a local or remote URL.

I have high internet bandwidth, so I don't think this is a connectivity issue.

What is the cause of this error?

> [percy] StatusCodeError 400 - {"errors":[{"status":"bad_request","detail":"Finalizing snapshot 558704687 failed: cannot finalize before all snapshot resources are uploaded. This is likely a client library bug, please make sure that content for all SHAs in 'missing-resources' from the snapshot response are uploaded before calling finalize."}]} | Fri Apr 16 2021 09:37:00 GMT-0400 (Eastern Daylight Time)

**Comment by wwilsman** [comment]
Hey @brenzy! Can you confirm you are using the latest version of the SDK?

**Comment by brenzy** [comment]
Hi @wwilsman.  Thanks for your quick reply.  I'm a little embarrassed to say that I didn't think of upgrading before asking my question.  The problem is random, but I have never as many successful runs in a row as I did after upgrading, so I will  close this issue.
